name: yt_feeds
description: Curated YouTube channel feeds
version: 1.0.0
repository: https://github.com/Craftplacer/yt_feeds

environment:
  sdk: '>=2.19.0-444.3.beta <3.0.0'

dependencies:
  args: ^2.3.0
  collection: ^1.17.0
  html: ^0.15.1
  http: ^0.13.5
  intl: ^0.17.0
  jiffy: ^5.0.0
  json_annotation: ^4.7.0
  mustache_template: ^2.0.0
  path: ^1.8.3
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.1
  xml: ^6.2.2

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  lints: ^2.0.0
  shelf_router_generator: ^1.0.5
  test: ^1.21.0
